import turtle as turtle
import random
def randomColor():
  r = random.randint(0,255)
  g = random.randint(0,255)
  b = random.randint(0,255)
  return(r, g, b)
screen = turtle.Screen()
screen.bgcolor(randomColor())
pen = turtle.Turtle()
pen.pensize(14)
pen.color(randomColor())
while True:
  turtle.tracer(10,0)
  pen.color(randomColor())
  pen.speed(0)
  pen.right(180)
  pen.forward(200)
  pen.right(180)
  for i in range(11):
    pen.forward(400)
    pen.right(90)
    pen.forward(10)
    pen.right(90)
    pen.forward(400)
    pen.left(90)
    pen.forward(10)
    pen.left(90)
  pen.left(90)
  pen.forward(200)
  for i in range(21):
    pen.forward(400)
    pen.right(90)
    pen.forward(10)
    pen.right(90)
    pen.forward(400)
    pen.left(90)
    pen.forward(10)
    pen.left(90)
  turtle.tracer(0,0)
  pen.right(270)
  pen.speed(1)
  pen.forward(220)
  pen.speed(0)
  pen.left(270)
  pen.speed(1)
  pen.forward(20)
  pen.speed(10)
  pen.right(270)
  pen.right(180)
  screen.update()